### ISSUE TITLE
error: ‘sp_track_get_availability’ was not declared in this scope

### ISSUE THREAD

**Issue by Olivia5k** [akezeke/spotyxbmc2#13]
I can't compile the latest commit in master (6fe85fa). The error I get is:
spotyXBMC/radio/RadioBackgroundLoader.cpp:61:127: error: ‘sp_track_get_availability’ was not declared in this scope

I looked around to see if I could quickfix it myself, but alas, I could not. I did however gather that the function was renamed from "sp_track_is_available()" in commit df266f14, if that could help.

Compile traceback and XBMC configuration data can be found in [this gist](https://gist.github.com/1434829). If I missed something needed for debugging, yell at me a little and I'll go get it!

**Comment by akezeke** [comment]
You have the wrong libspotify version, make sure version 10 is
installed and used!

/David

2011/12/5 Lowe Thiderman
reply@reply.github.com:

**Comment by Olivia5k** [comment]
Hah, I knew it was something simple! Thanks for the incredibly quick response! :)
