### ISSUE TITLE
album sorting in spotyxbmc

### ISSUE THREAD

**Issue by G1sbert** [akezeke/spotyxbmc2#17]
hi,

thank for your great work to implement spotify to xbmc, one thing i miss is the ability to sort the albums of an artist, like its done in the spotify client. My suggestion would be to first show the artist albums, then the singles and then the compilations. Do you think its possible to implement this to spotyxbmc?
I found an module in libspotify wich i think, should help you:
http://developer.spotify.com/en/libspotify/docs/group__album.html#ga019b49a9d1633b61daa79c80ea01d5c3

thanks for your help
G1sbert

**Comment by akezeke** [comment]
Sure, 

But this has nothing to do with spotyXBMC, the album sorting is up to XBMC, I just provide the albums!
