### ISSUE TITLE
Multiple album playlist metadata

### ISSUE THREAD

**Issue by ghost** [akezeke/spotyxbmc2#2]
All my playlists contain songs from multiple albums (e.g. http://open.spotify.com/user/charliebrooker/playlist/1cbjbEfXuZesvIYHnN9ilP)

Only the 1st album art is displayed from Spotify. Other tracks that are already in my local library also show the album art, but any other art is not displayed.

This is on Windows 7 64 bit, built from your commit 5e455b5f on 14/07/2011

Let me know if providing a debug log would help.

**Comment by akezeke** [comment]
Well, this issue still applies. It seems to be a bug in the API, I have implemented the feature and when the API starts deliver nice playlist thumbs they "should" appear in XBMC.

**Comment by ghost** [comment]
Fixed in new implementation
