### ISSUE TITLE
Skipping incompatible /usr/local/lib/libspotify.so when searching for -lspotify

### ISSUE THREAD

**Issue by antoinegomez** [akezeke/spotyxbmc2#22]
Hello, 

Here is what I got when compiling :

/usr/bin/ld: skipping incompatible /usr/local/lib/libspotify.so when searching for -lspotify

I'm on Linux Ubuntu 11.10 alternate minimal install, no desktop.

I don't understand why I got this error since I have libspotify installed :

ls -l /usr/local/lib/libspotify.so
lrwxrwxrwx 1 root root 21 2012-02-20 20:41 /usr/local/lib/libspotify.so -> libspotify.so.10.1.16

Any idea ? Do you need more informations ?

Thank you !

**Comment by antoinegomez** [comment]
Delete this issue. I'm a dumb. So used to work on 64bit systems that I forgot I installed 32bit ubuntu on my HTPC :-/

**Comment by lukasnagl** [comment]
Don't delete this. Just made the same mistake, found this, and simply reinstalled the correct libspotify. Thanks antoinegomez! :)
