### ISSUE TITLE
No playlists in web interface AWXi

### ISSUE THREAD

**Issue by antoinegomez** [akezeke/spotyxbmc2#24]
Hello,

spotyXBMC2 is running fine on my side, just some little freezes at the start of a song or when I leap backward/forward but it's fine (for now :D).

My issue is about not having playlists in my web interface and my goal was being able to control Spotify with XBMC via wireless at home.

I have some albums in the view albums, some I starred, artist view is in an infinite loop. The only thing working in the interface is "Now playing" where I'm able to view the current playlist.

Am I missing something ?

I compiled spotyXBMC2 a week or two ago. Running on 32bit Ubuntu minimal (no desktop).

AWXi version is 0.5.

Thanks !

**Comment by neoflex** [comment]
The JSON Api hasn't been completely adapted to deal with spotify tracks, artists, albums and playlists. For now, only the GetAlbums method has been modified. The client (here AWX) also has to be modified. With the defaults web interface it should work for starred albums.

**Comment by neoflex** [comment]
I have modified AWXi to make it compatible with SpotyXBMC2:

You'll find it there: https://github.com/neoflex/AWX-Eden/tree/spotiXBMC2

You'll also need last version of spotyXBMC2.

**Comment by antoinegomez** [comment]
Thank you :-*

I will test it tonight.

2012/5/3 Valentin Grouès <
reply@reply.github.com
