### ISSUE TITLE
Files mentioned in readme moved

### ISSUE THREAD

**Issue by chrstnwhlrt** [akezeke/spotyxbmc2#28]
There are some changes in the dir structure, not yet mentioned in the readme:
- The folder "xbmc/MusicDatabaseDirectory/" moved to "/xbmc/filesystem/MusicDatabaseDirectory/"
- There is a spelling failure in "xbmc/music/Windows/GuiWindowMusicNav.cpp", correct is: "/xbmc/music/windows/GUIWindowMusicNav.cpp"
- And there were changes made in "xbmc/dialogs/GUIDialogContextMenu.h", the 4 spotify constants of course.. 
- Also found that "xbmc/Application.h" changed
- ...and "xbmc/settings/AdvancedSettings.h", "xbmc/settings/AdvancedSettings.cpp"
- Ahhhhhr and you also changed the "configure.in"

please correct this in the readme, I'am merging your code with the xbmc-pvr right now..

regards

OK code merged successfully... corrected list:
### Added files:

xbmc/music/spotyXBMC/*
addons/plugin.music.spotyXBMC/*
addons/skin.confluence/media/flagging/audio/spotify.png
### Modified files:

xbmc/cores/paplayer/CodecFactory.cpp
xbmc/filesystem/MusicSearchDirectory.cpp
xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbum.cpp
xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeArtist.cpp
xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeOverview.cpp
xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeSong.cpp
xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeTop100.cpp
xbmc/music/windows/GUIWindowMusicBase.cpp
xbmc/music/windows/GUIWindowMusicNav.cpp
xbmc/dialogs/GUIDialogContextMenu.h
xbmc/music/Makefile
xbmc/settings/Settings.cpp
xbmc/settings/AdvancedSettings.h
xbmc/settings/AdvancedSettings.cpp
xbmc/Application.h
xbmc/Application.cpp
xbmc/GUIInfoManager.cpp
configure.in

**Comment by akezeke** [comment]
Thanks!

**Comment by chrstnwhlrt** [comment]
I'm not sure, but some of the files only differ to the pvr branch in a member called something like "..servermode..", this doesn't seem to be necessary to merge, as I recognized yesterday..
