### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by mathroc** [akezeke/spotyxbmc2#30]
in xbmc/Application.php, bool bFullScreen is declared twice (lines ~780~810)

can't find how to upload a patch, so here it is : 

--- xbmc/Application.cpp.o      2012-03-30 16:28:40.760074100 +0200
+++ xbmc/Application.cpp        2012-03-30 16:29:53.132071526 +0200
@@ -765,17 +765,17 @@
     if (g_advancedSettings.m_startFullScreen && g_guiSettings.m_LookAndFeelResolution == RES_WINDOW)
       g_guiSettings.m_LookAndFeelResolution = RES_DESKTOP;
-  bool bFullScreen = false;
  #ifdef TARGET_DARWIN_OSX
   // force initial window creation to be windowed, if fullscreen, it will switch to it below
  // fixes the white screen of death if starting fullscreen and switching to windowed.
-  bool bFullScreen = false;
  if (!g_Windowing.CreateNewWindow("XBMC", bFullScreen, g_settings.m_ResInfo[RES_WINDOW], OnEvent))
  { 
   CLog::Log(LOGFATAL, "CApplication::Create: Unable to create window");
   return false;
  }
  #else
-  bool bFullScreen = g_guiSettings.m_LookAndFeelResolution != RES_WINDOW;
-  bFullScreen = g_guiSettings.m_LookAndFeelResolution != RES_WINDOW;
  if (!g_Windowing.CreateNewWindow("XBMC", bFullScreen, g_settings.m_ResInfo[g_guiSettings.m_LookAndFeelResolution], OnEvent))
  { 
   CLog::Log(LOGFATAL, "CApplication::Create: Unable to create window");
  @@ -793,14 +793,13 @@
  #ifdef **APPLE**
   // force initial window creation to be windowed, if fullscreen, it will switch to it below
   // fixes the white screen of death if starting fullscreen and switching to windowed.
-    bool bFullScreen = false;
   if (!g_Windowing.CreateNewWindow("XBMC", bFullScreen, g_settings.m_ResInfo[RES_WINDOW], OnEvent))
   { 
     CLog::Log(LOGFATAL, "CApplication::Create: Unable to create window");
     return false;
   }
  #else
-    bool bFullScreen = g_guiSettings.m_LookAndFeelResolution != RES_WINDOW;
-    bFullScreen = g_guiSettings.m_LookAndFeelResolution != RES_WINDOW;
   if (!g_Windowing.CreateNewWindow("XBMC", bFullScreen, g_settings.m_ResInfo[g_guiSettings.m_LookAndFeelResolution], OnEvent))
   { 
     CLog::Log(LOGFATAL, "CApplication::Create: Unable to create window");

**Comment by neoflex** [comment]
it has been fixed for Eden and master branch, thank you.
