### ISSUE TITLE
feature request: 320kbps

### ISSUE THREAD

**Issue by johnkristian** [akezeke/spotyxbmc2#32]
Hi.
320Kbps setting is now available on iPhone and Android (beta) and it's reasonable to think that it will be implemented in pc/linux/mac client soon.

Will you add this feature when it's available? Prettyplease? :)

**Comment by neoflex** [comment]
It's already there. You just have to enable high bitrate audio in the plugin's settings.

**Comment by johnkristian** [comment]
I tought that was 160Kbps?

**Comment by neoflex** [comment]
160 Kbps is the low bandwidth option I think.
Just have a look at https://github.com/akezeke/spotyxbmc2/blob/master/xbmc/music/spotyXBMC/player/Codec.cpp, you'll see that there is a switch between 160 and 320 ;)
On the aeon nox skin, I can see 320kbps when I play a spotify song.

**Comment by johnkristian** [comment]
ooh :) Nice. Normally, 160Kbps is refered to as "high" and 320 "extreme". But this is very good :)
