### ISSUE TITLE
Installing in Crystalbuntu (Ubuntu 8.0.4 - XBMC 11 RC3)

### ISSUE THREAD

**Issue by rljb1804** [akezeke/spotyxbmc2#41]
Can anybody help me installing? I get a lot of error's when trying to run the command :

sudo apt-get install git-core make g++ gcc gawk pmount libtool nasm yasm automake cmake gperf zip unzip bison libsdl-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libsdl-mixer1.2-dev libfribidi-dev liblzo2-dev libfreetype6-dev libsqlite3-dev libogg-dev libasound2-dev python-sqlite libglew-dev libcurl3 libcurl4-gnutls-dev libxrandr-dev libxrender-dev libmad0-dev libogg-dev libvorbisenc2 libsmbclient-dev libmysqlclient-dev libpcre3-dev libdbus-1-dev libhal-dev libhal-storage-dev libjasper-dev libfontconfig-dev libbz2-dev libboost-dev libenca-dev libxt-dev libxmu-dev libpng-dev libjpeg-dev libpulse-dev mesa-utils libcdio-dev libsamplerate-dev libmpeg3-dev libflac-dev libiso9660-dev libass-dev libssl-dev fp-compiler gdc libmpeg2-4-dev libmicrohttpd-dev libmodplug-dev libssh-dev gettext cvs python-dev libyajl-dev libboost-thread-dev libplist-dev libusb-dev libudev-dev libtinyxml-dev

to get all the dependencies up to date. It appears to hang on MySQL.

The output is as follows.

Reading package lists... Done
Building dependency tree  
Reading state information... Done
git-core is already the newest version.
make is already the newest version.
make set to manually installed.
g++ is already the newest version.
g++ set to manually installed.
gcc is already the newest version.
gcc set to manually installed.
libtool is already the newest version.
automake is already the newest version.
cmake is already the newest version.
zip is already the newest version.
unzip is already the newest version.
Note, selecting libsdl1.2-dev instead of libsdl-dev
libsdl1.2-dev is already the newest version.
libsdl-image1.2-dev is already the newest version.
libsdl-mixer1.2-dev is already the newest version.
libfribidi-dev is already the newest version.
liblzo2-dev is already the newest version.
libfreetype6-dev is already the newest version.
libsqlite3-dev is already the newest version.
libogg-dev is already the newest version.
libasound2-dev is already the newest version.
Note, selecting libglew1.5-dev instead of libglew-dev
libglew1.5-dev is already the newest version.
libcurl4-gnutls-dev is already the newest version.
libmad0-dev is already the newest version.
libogg-dev is already the newest version.
libvorbisenc2 is already the newest version.
Package libmysqlclient-dev is a virtual package provided by:
  libmysqlclient15-dev 5.0.96-0ubuntu3
You should explicitly select one to install.
E: Package libmysqlclient-dev has no installation candidate

Also, running the 'single command' for the update returns the following.

$ sudo apt-get build-dep xbmc
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Build-Depends dependency for xbmc cannot be satisfied because no available versions of package debhelper can satisfy version requirements

Please advise, because now, I can't run ./configure or ./make .....

I would like to have it up and running, if possible.

Hope to hear from anyone soon,

Ronald.

**Comment by neoflex** [comment]
It doesn't seem to be related specifically to spotyXBMC2. You should ask on Ubuntu's or xbmc forum I think.

**Comment by rljb1804** [comment]
Thanks. I'll give that a try!
