### ISSUE TITLE
Compiling windows 12.2

### ISSUE THREAD

**Issue by ErlendSB** [akezeke/spotyxbmc2#57]
Currently unable to compile on windows. Project file seems to be missing libspotify

**Comment by wilderkaiser** [comment]
i see ... not possible to add it from this source? https://developer.spotify.com/technologies/libspotify/

**Comment by ErlendSB** [comment]
I tried using the project file from the 12.1 branch, which have the dependencies. But I ran into more compilation errors. I'll see if I can at least give you guys some logs when I get home from work. This C++ programming is a bit beyond my skillset, but if I manage to get a build going, I'll post a pull request.

**Comment by wilderkaiser** [comment]
That sounds good! I already have running it on the 11 eden and i am very impressed about how fast this is working. Another Q. Fanarts is not working, Feature/Bug or any Idea?

**Comment by bigmacpaddy** [comment]
I managed to build the latest master version, by copying the missing files from VS2010Express folder in 12.1. Shows as 12.2 when installed and running.

But i get the skipping errors when changing songs. https://github.com/akezeke/spotyxbmc2/pull/45

More info here: http://forum.xbmc.org/showthread.php?tid=67012&page=116

Not sure if any of this helps.

**Comment by neoflex** [comment]
Hi,

If someone has a working solution for windows, could you please make a pull request?
I personnaly only test on ubuntu ;)
