### ISSUE TITLE
Spotyxbmc2 crashes on startup

### ISSUE THREAD

**Issue by Rainman73** [akezeke/spotyxbmc2#6]
I successfully built and installed spotyxbmc2 on my HTPC running Ubuntu. Thanks for that!

I use autologin/autostart so that xbmc starts when I switch on my HTPC, as I did with spotyxbmc1. But after startup, about 10-15 seconds after xbmc is started, it crashes (and automatically restarts twice, after that it quits saying that it crashed three times in ~ 40 seconds), I usually have some logging on the console that says that it was trying to get thumbs from the store or something along those lines. Sometimes I also get a stack trace (illegal instruction).

When I restart my htpc it sometimes works successfully (1 in 4 times) and I have been able to play music from spotify with spotyxbmc2 before.

If you need any logfiles or some such, please let me know and I will try to provide them!

Best regards,

Ramon Verbruggen
ramon.github@famverbruggen.nl

**Comment by Rainman73** [comment]
Duhh...still getting used to 'git'...I just pulled the latest changes (I hope that means I am now up to date with the master branch), and now building new version, will update when I know if that changed anything.

**Comment by Rainman73** [comment]
OK...sorry for the noise...after pulling https://github.com/akezeke/spotyxbmc2/commit/4ef626b8ff1186ec67245ce6bd9e8d978433054c it now seems to work...listening to Volbeat :-)

Sorry again for the noise!

**Comment by akezeke** [comment]
Glad it worked out :)
